### PR TITLE
fix: set gesture-reader's usageStatistics depending on the flicking's

### PR DESCRIPTION
**Pull request by dotaitch**

### CODE REVIEW

**Comment by seonim-ryu** [comment]
[8/8] 이견 없습니다. 고생하셨어요! :)

**Comment by dotaitch** [comment]
retest this please

**Comment by dotaitch** [comment]
retest this please

**Comment by dotaitch** [comment]
retest this please

**Comment by dotaitch** [comment]
retest this please

**Comment by dotaitch** [comment]
retest this please

**Comment by dotaitch** [comment]
retest this please

**Pull request merged**
